In [1]:
import numpy as np

In [2]:
import numpy as np

class RNN_core:
    def __init__(self, w_x=None, w_h=None, b=None):
        self.w_x = np.random.rand() if w_x is None else w_x
        self.w_h = np.random.rand() if w_h is None else w_h
        self.b = np.random.rand() if b is None else b

    def Relu(self, x):
        return max(0, x)

    def forward(self, x, h):
        return self.Relu(self.w_x * x + self.w_h * h + self.b)

In [3]:
h0 = 0.0
x = 2.0

rnn = RNN_core()
h1 = rnn.forward(x, h0)
print(h1)

1.3593541713781145


In [15]:
class RNN():
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.wxh = np.random.randn(hidden_size, input_size) * 0.01
        self.whh = np.random.randn(hidden_size, hidden_size) * 0.01
        self.why = np.random.randn(output_size, hidden_size) * 0.01

        self.bh = np.zeros((hidden_size, 1))
        self.by = np.zeros((output_size, 1))

    def softmax(self, x):
        x = x - np.max(x)
        exp_x = np.exp(x)
        return exp_x / np.sum(exp_x)

    def forward(self, x):

        h_old = np.zeros((self.hidden_size, 1))

        self.caches = []
        outputs = []

        for val in x:

            val = val.reshape(-1,1)

            z = (self.wxh @ val + self.whh @ h_old + self.bh)
            h_current = np.tanh(z)

            y_pred = self.why @ h_current + self.by

            outputs.append(y_pred)
            self.caches.append((x, h_old, z, h_current))

            h_old = h_current

        return outputs

    def loss(self, outputs, targets):

        loss = 0.0

        probabilities = []

        for y, target in zip(outputs, targets):

            p = self.softmax(y)

            probabilities.append(p)

            loss -= np.log(p[target])

        return loss, probabilities

In [16]:
rnn = RNN(input_size=3, hidden_size=4, output_size=2)

In [17]:
inputs = [ np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]

In [18]:
output = rnn.forward(inputs)
output

[array([[-0.00019266],
        [ 0.00033784]]),
 array([[-0.00022511],
        [ 0.0002577 ]]),
 array([[-2.87973559e-06],
        [-9.69209539e-05]])]

In [19]:
targets = [0, 1, 0]
loss, probabilities = rnn.loss(output, targets)

print("Loss:", loss)

for p in probabilities:
    print(p)

Loss: [2.07941843]
[[0.49986737]
 [0.50013263]]
[[0.4998793]
 [0.5001207]]
[[0.50002351]
 [0.49997649]]
