In [1]:
import torch
import numpy as np

In [2]:
tensor_1d = torch.tensor(5)
tensor_2d = torch.tensor([1,2,3,4,5])
tensor_3d = torch.tensor([
    [1,2,3,4,5],
    [1,4,9,16,25]
])

In [3]:
tensor_1d

tensor(5)

In [4]:
tensor_2d

tensor([1, 2, 3, 4, 5])

In [6]:
tensor_3d

tensor([[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]])

In [12]:
tensor_1d.ndim

0

In [13]:
tensor_2d.ndim

1

In [14]:
tensor_3d.ndim

2

In [15]:
tensor_1d.item()

5

In [19]:
tensor_1d.shape

torch.Size([])

In [20]:
tensor_2d.shape

torch.Size([5])

In [21]:
tensor_3d.shape

torch.Size([2, 5])

In [22]:
rand_tensor = torch.rand( size = (3, 3))

In [23]:
rand_tensor

tensor([[0.3225, 0.6205, 0.8751],
        [0.2499, 0.5937, 0.5530],
        [0.4021, 0.1788, 0.9887]])

In [24]:
rand_tensor.dtype

torch.float32

In [25]:
weight_tensor = torch.zeros( size = (3, 4))

In [26]:
weight_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones_tensor = torch.ones( size = (3, 1))

In [29]:
ones_tensor

tensor([[1.],
        [1.],
        [1.]])

In [30]:
range_tensor = torch.arange(start = -3, end = 3, step = 0.5)

In [31]:
range_tensor

tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,
         1.0000,  1.5000,  2.0000,  2.5000])

In [32]:
rand_tensor.device

device(type='cpu')

In [33]:
device = torch.device('cuda')

In [37]:
random_tensor = torch.rand( size = (3, 3))

In [38]:
random_tensor

tensor([[0.6057, 0.8269, 0.3913],
        [0.7024, 0.9614, 0.3663],
        [0.1295, 0.5778, 0.6912]])

In [39]:
random_tensor + 10

tensor([[10.6057, 10.8269, 10.3913],
        [10.7024, 10.9614, 10.3663],
        [10.1295, 10.5778, 10.6912]])

In [40]:
random_tensor.device

device(type='cpu')

In [41]:
gpu_tensor = torch.tensor([[1,2],
                          [3,4]], device = device)

In [42]:
gpu_tensor

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [43]:
gpu_tensor.device

device(type='cuda', index=0)

In [44]:
gpu_tensor + 1

tensor([[2, 3],
        [4, 5]], device='cuda:0')

In [45]:
gpu_tensor * 2

tensor([[2, 4],
        [6, 8]], device='cuda:0')

In [46]:
gpu_tensor

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [47]:
gpu_tensor += 1

In [48]:
gpu_tensor

tensor([[2, 3],
        [4, 5]], device='cuda:0')

Matrix Multiplictaion ----->

In [2]:
tensor_input = torch.rand( size = (30, 5))
tensor_b = torch.rand( size = (5, 2))

In [3]:
tensor_input

tensor([[0.5665, 0.3930, 0.1884, 0.0540, 0.1099],
        [0.8728, 0.4099, 0.8361, 0.6183, 0.6283],
        [0.8594, 0.5787, 0.4452, 0.8379, 0.5547],
        [0.3717, 0.6474, 0.8221, 0.6156, 0.7948],
        [0.4890, 0.2467, 0.1938, 0.5879, 0.4001],
        [0.8667, 0.1097, 0.8277, 0.0201, 0.5220],
        [0.0589, 0.9750, 0.2365, 0.9758, 0.1369],
        [0.2258, 0.1855, 0.7533, 0.8621, 0.5096],
        [0.6363, 0.4559, 0.6788, 0.4490, 0.6384],
        [0.0067, 0.0928, 0.8452, 0.3010, 0.3836],
        [0.1479, 0.4371, 0.3207, 0.5885, 0.2830],
        [0.2319, 0.7074, 0.6399, 0.2085, 0.4287],
        [0.1996, 0.7257, 0.3978, 0.4039, 0.6440],
        [0.5837, 0.4850, 0.9148, 0.7276, 0.7633],
        [0.2689, 0.5871, 0.0649, 0.6488, 0.3274],
        [0.1804, 0.9419, 0.4993, 0.3302, 0.1124],
        [0.2964, 0.9885, 0.2123, 0.0907, 0.4847],
        [0.3427, 0.7859, 0.6616, 0.0584, 0.8541],
        [0.5348, 0.7463, 0.9044, 0.8337, 0.4408],
        [0.4775, 0.5336, 0.3289, 0.2247, 0.9484],


In [4]:
tensor_b

tensor([[0.2155, 0.9611],
        [0.8178, 0.1858],
        [0.2885, 0.5542],
        [0.9945, 0.4072],
        [0.0552, 0.5650]])

In [5]:
output_tensor = tensor_input @ tensor_b

In [6]:
output_tensor

tensor([[0.5576, 0.8060],
        [1.4142, 1.9852],
        [1.6508, 1.8349],
        [1.5028, 1.6329],
        [0.9698, 1.0887],
        [0.5641, 1.6152],
        [1.8563, 0.8436],
        [1.3032, 1.3079],
        [1.1876, 1.6160],
        [0.6416, 0.8314],
        [1.0827, 0.8006],
        [1.0442, 1.0361],
        [1.1885, 1.0755],
        [1.5521, 1.8857],
        [1.2202, 0.8527],
        [1.2878, 0.8231],
        [1.0506, 0.8970],
        [1.0127, 1.3485],
        [1.8401, 1.7425],
        [0.9100, 1.3677],
        [0.9422, 1.2413],
        [1.9530, 1.6508],
        [0.7646, 1.0551],
        [0.8819, 1.2429],
        [0.6528, 0.4356],
        [0.7663, 0.8809],
        [0.7914, 1.7472],
        [1.0353, 1.4096],
        [0.9426, 1.2867],
        [0.7016, 1.1795]])