In [1]:
import torch
import numpy as np

In [2]:
tensor_1d = torch.tensor(5)
tensor_2d = torch.tensor([1,2,3,4,5])
tensor_3d = torch.tensor([
    [1,2,3,4,5],
    [1,4,9,16,25]
])

In [3]:
tensor_1d

tensor(5)

In [4]:
tensor_2d

tensor([1, 2, 3, 4, 5])

In [6]:
tensor_3d

tensor([[ 1,  2,  3,  4,  5],
        [ 1,  4,  9, 16, 25]])

In [12]:
tensor_1d.ndim

0

In [13]:
tensor_2d.ndim

1

In [14]:
tensor_3d.ndim

2

In [15]:
tensor_1d.item()

5

In [19]:
tensor_1d.shape

torch.Size([])

In [20]:
tensor_2d.shape

torch.Size([5])

In [21]:
tensor_3d.shape

torch.Size([2, 5])

In [22]:
rand_tensor = torch.rand( size = (3, 3))

In [23]:
rand_tensor

tensor([[0.3225, 0.6205, 0.8751],
        [0.2499, 0.5937, 0.5530],
        [0.4021, 0.1788, 0.9887]])

In [24]:
rand_tensor.dtype

torch.float32

In [25]:
weight_tensor = torch.zeros( size = (3, 4))

In [26]:
weight_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones_tensor = torch.ones( size = (3, 1))

In [29]:
ones_tensor

tensor([[1.],
        [1.],
        [1.]])

In [30]:
range_tensor = torch.arange(start = -3, end = 3, step = 0.5)

In [31]:
range_tensor

tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,
         1.0000,  1.5000,  2.0000,  2.5000])

In [32]:
rand_tensor.device

device(type='cpu')

In [33]:
device = torch.device('cuda')

In [37]:
random_tensor = torch.rand( size = (3, 3))

In [38]:
random_tensor

tensor([[0.6057, 0.8269, 0.3913],
        [0.7024, 0.9614, 0.3663],
        [0.1295, 0.5778, 0.6912]])

In [39]:
random_tensor + 10

tensor([[10.6057, 10.8269, 10.3913],
        [10.7024, 10.9614, 10.3663],
        [10.1295, 10.5778, 10.6912]])

In [40]:
random_tensor.device

device(type='cpu')

In [41]:
gpu_tensor = torch.tensor([[1,2],
                          [3,4]], device = device)

In [42]:
gpu_tensor

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [43]:
gpu_tensor.device

device(type='cuda', index=0)

In [44]:
gpu_tensor + 1

tensor([[2, 3],
        [4, 5]], device='cuda:0')

In [45]:
gpu_tensor * 2

tensor([[2, 4],
        [6, 8]], device='cuda:0')

In [46]:
gpu_tensor

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [47]:
gpu_tensor += 1

In [48]:
gpu_tensor

tensor([[2, 3],
        [4, 5]], device='cuda:0')