In [1]:
import numpy as np

In [3]:
input  = np.random.randn(50, 5)

In [4]:
input

array([[-8.96915247e-02, -2.22662555e-01,  7.58825775e-01,
        -1.39581916e+00, -3.93678252e-01],
       [ 2.69402592e-01,  1.45863888e-01,  4.30388965e-01,
         2.94943406e-01, -9.90150253e-01],
       [ 1.21052561e-01, -3.99069584e-01,  1.59995791e-01,
         1.24126980e+00,  5.09556306e-01],
       [ 2.37766580e-02,  5.58692968e-01, -2.15467656e+00,
         5.83276934e-01,  9.63362032e-02],
       [ 2.51023218e-01,  1.48992937e+00,  1.13508844e-01,
        -7.97999374e-01, -1.01799315e-01],
       [-4.83681000e-01,  9.34467184e-02,  3.41619648e-01,
        -6.87453900e-02, -1.12144825e+00],
       [ 1.20994239e+00,  2.01781075e-01, -6.71946798e-01,
         1.01579818e+00,  1.47547843e-01],
       [ 8.10593566e-01, -9.32276345e-01, -9.30379852e-01,
        -8.99784575e-01, -1.68935635e-01],
       [ 1.74081922e-01,  2.42142895e+00,  1.86352159e+00,
        -2.77038311e+00,  8.71500159e-01],
       [-6.30577850e-02,  1.23208231e-01, -5.99334291e-01,
         1.34427063e+00

In [5]:
len(input[1])

5

In [7]:
layer1_weights = np.random.randn(len(input[1]), 3) * np.sqrt(2/3)

In [8]:
layer1_weights

array([[ 0.35339136, -0.02988207, -0.17381122],
       [-0.74101444, -0.30090313,  1.03216915],
       [-1.80278982,  0.36687127, -0.61765017],
       [-1.57785149, -0.53781436,  0.36377289],
       [-0.09980756, -0.4513051 ,  0.17298896]])

In [9]:
def sigmoid(z):
    return 1/(1 + np.exp(-np.clip(z, -100, 100)))

In [10]:
bias = np.zeros((1, 3))

In [11]:
z = np.dot(input, layer1_weights) + bias

In [12]:
z

array([[ 1.00698399,  1.276432  , -1.25878805],
       [-1.15533596,  0.3941912 , -0.22609145],
       [-1.95934051, -0.72237624,  0.00791889],
       [ 2.54889241, -1.31648361,  2.13221477],
       [ 0.0493025 ,  0.0609357 ,  1.11621903],
       [-0.63564345,  0.65475299, -0.2494853 ],
       [-0.12806571, -0.95629006,  0.80804267],
       [ 4.09115381,  0.4751316 , -0.88504911],
       [-0.80806171,  1.04649441,  0.46103208],
       [-1.09035435, -0.68948279,  0.88671519],
       [-0.3873972 , -0.4392981 ,  0.33721488],
       [-4.31403828, -0.53712074,  1.9482706 ],
       [-1.62976172, -0.36279585, -0.26176148],
       [ 1.39892358, -0.01804652,  0.50824093],
       [ 1.88166462,  1.1926605 , -1.78846628],
       [ 3.78685077,  0.34790261,  0.58208911],
       [ 0.03852306,  0.75325342,  0.30868341],
       [ 0.14357853,  0.86312578, -0.32484141],
       [-0.83245717,  0.2749755 , -1.67039487],
       [-1.63577744, -0.62640099,  0.05881385],
       [-0.96219235, -0.32323368,  0.569

In [13]:
a = sigmoid(z)

In [14]:
a

array([[0.7324295 , 0.78184181, 0.22118259],
       [0.2395158 , 0.59729124, 0.44371669],
       [0.12353844, 0.32686993, 0.50197971],
       [0.92749907, 0.21140392, 0.89399508],
       [0.51232313, 0.51522921, 0.75328671],
       [0.34623201, 0.65808074, 0.43795019],
       [0.46802726, 0.2776216 , 0.69169225],
       [0.98355503, 0.61659761, 0.29213257],
       [0.30830369, 0.74010116, 0.61325899],
       [0.25155156, 0.33414814, 0.70821184],
       [0.40434403, 0.39190823, 0.58351383],
       [0.01320277, 0.36885763, 0.87525795],
       [0.16386301, 0.41028294, 0.43493075],
       [0.80201302, 0.49548849, 0.62439402],
       [0.86780221, 0.76721656, 0.14326087],
       [0.97783553, 0.58610888, 0.64154797],
       [0.50962957, 0.67988719, 0.57656386],
       [0.5358331 , 0.70331331, 0.41949631],
       [0.30312577, 0.56831397, 0.15837154],
       [0.16304045, 0.34832705, 0.51469923],
       [0.27643946, 0.41988788, 0.63868247],
       [0.99431668, 0.78857026, 0.20536968],
       [0.

In [15]:
x = input