In [1]:
import numpy as np

In [3]:
input  = np.random.randn(5)

In [4]:
input

array([-1.07604988,  2.08503405,  0.05537973,  0.6825879 ,  0.10306561])

In [8]:
weights = np.random.randn(len(input), 3) * np.sqrt(2/3)

In [9]:
weights

array([[ 0.0908473 , -0.24349442, -0.23544612],
       [-0.4739084 , -1.22140246,  1.4928016 ],
       [ 0.67383841, -0.73642987,  2.002663  ],
       [ 0.2741818 ,  0.29349089, -0.83672993],
       [-0.98441958,  0.70194175, -0.36907466]])

In [7]:
def sigmoid(z):
    return 1/(1 + np.exp(-np.clip(z, -100, 100)))

In [11]:
bias = np.zeros((1, 3))

In [12]:
z = np.dot(input, weights) + bias

In [13]:
z

array([[-0.96286101, -2.05275748,  2.86762024]])

In [14]:
a = sigmoid(z)

In [15]:
a

array([[0.27630574, 0.11377405, 0.94622238]])

In [16]:
x = input

In [17]:
x

array([-1.07604988,  2.08503405,  0.05537973,  0.6825879 ,  0.10306561])